# Generated by Django 5.0.2 on 2024-02-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_auto_20220302_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='position_id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='middlename',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
